//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossFinance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agreement
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public int PersonId { get; set; }
        public int FinancialStateId { get; set; }
    
        public virtual financialstate financialstate { get; set; }
        public virtual person person { get; set; }
    }
}
